# Generated by Django 4.1.3 on 2022-12-23 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('role', models.CharField(default='EMPLOYE', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, upload_to='images/', verbose_name='User Image')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Name Departement')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='ProjectName')),
                ('date_debut', models.DateField(verbose_name='StartDateProject')),
                ('date_fin', models.DateField(verbose_name='EndDateProjects')),
                ('description', models.CharField(max_length=500, verbose_name='ProjectDescription ')),
                ('etat', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('NON_DEMARRE', 'non_demarre'), ('EN_COURS', 'en_cours'), ('TERMINE', 'termine')], default='NON_DEMARRE', max_length=40)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.departement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Task Name')),
                ('valeur', models.FloatField(verbose_name='Percent Project')),
                ('estRealisee', models.BooleanField(default=False)),
                ('date_debut', models.DateField(verbose_name='Start Date Task')),
                ('date_fin', models.DateField(verbose_name='End Date Task')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_doc', models.CharField(max_length=50, verbose_name='Name Document')),
                ('doc', models.FileField(upload_to='docs/')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.projet')),
            ],
        ),
    ]
